#!/usr/bin/env sh
# GENERATED by tools/ai/compile-command-policy.php from docs/ai/command-policy.tiers.yaml.
# DO NOT EDIT BY HAND. Dependency-free: POSIX sh only (no yq, no jq, no PHP at runtime).
#
# Reads a command string on stdin (already compacted by the caller) and prints a decision:
#   deny:<reason>   and exits 1
#   ask:<reason>    and exits 0
#   allow           and exits 0
# Precedence: deny > ask > allow > default allow-through.
set -u

cmd="$(cat)"
cmd="$(printf '%s' "$cmd" | tr -s '[:space:]' ' ')"
cmd="${cmd# }"
cmd="${cmd% }"

case "$cmd" in
    "rm "*)
        printf 'deny:%s\n' 'denied by tiered command policy: rm *'
        exit 1
        ;;
    "git reset --hard "*)
        printf 'deny:%s\n' 'denied by tiered command policy: git reset --hard *'
        exit 1
        ;;
    "git clean "*)
        printf 'deny:%s\n' 'denied by tiered command policy: git clean *'
        exit 1
        ;;
    "bash scripts/ai/ai-verify.sh "*)
        printf 'ask:%s\n' 'confirm required by tiered command policy: bash scripts/ai/ai-verify.sh *'
        exit 0
        ;;
    "bash scripts/ai/pack-context.sh "*)
        printf 'ask:%s\n' 'confirm required by tiered command policy: bash scripts/ai/pack-context.sh *'
        exit 0
        ;;
    "git commit"*)
        printf 'ask:%s\n' 'confirm required by tiered command policy: git commit*'
        exit 0
        ;;
    "bash scripts/ai/ai-edit.sh "*)
        printf 'ask:%s\n' 'confirm required by tiered command policy: bash scripts/ai/ai-edit.sh *'
        exit 0
        ;;
    "bash scripts/ai/ai-rollback.sh "*)
        printf 'ask:%s\n' 'confirm required by tiered command policy: bash scripts/ai/ai-rollback.sh *'
        exit 0
        ;;
    "php tools/ai/install-ai-kit.php "*)
        printf 'ask:%s\n' 'confirm required by tiered command policy: php tools/ai/install-ai-kit.php *'
        exit 0
        ;;
    "pwd")
        printf 'allow\n'
        exit 0
        ;;
    "date "*)
        printf 'allow\n'
        exit 0
        ;;
    "bash scripts/ai/ai-search.sh "*)
        printf 'allow\n'
        exit 0
        ;;
    "bash scripts/ai/preview-file.sh "*)
        printf 'allow\n'
        exit 0
        ;;
    "bash scripts/ai/query-usage.sh "*)
        printf 'allow\n'
        exit 0
        ;;
    "git status"*)
        printf 'allow\n'
        exit 0
        ;;
    "git diff"*)
        printf 'allow\n'
        exit 0
        ;;
    "git log"*)
        printf 'allow\n'
        exit 0
        ;;
    "php tools/ai/validate-"*".php "*)
        printf 'allow\n'
        exit 0
        ;;
    *)
        printf 'allow\n'
        exit 0
        ;;
esac
