<?php

declare(strict_types=1);

/**
 * Shared generated-file header helpers.
 *
 * This is the single source of truth for the markdown "GENERATED — DO NOT EDIT"
 * header used across installer-rendered files. It was previously duplicated
 * inline in tools/ai/install/docs.php and tools/ai/install/manifest.php; both now
 * require this file instead. The function_exists guard keeps the require chain
 * (core.php -> manifest.php + docs.php) safe from double-definition fatals.
 */

if (!function_exists('aiInstallerGeneratedMarkdownHeader')) {
    /**
     * The canonical hard "DO NOT EDIT" header for fully generated markdown files.
     */
    function aiInstallerGeneratedMarkdownHeader(string $source): string
    {
        return '<!-- GENERATED — DO NOT EDIT: generated by ' . $source . '. -->' . "\n\n";
    }
}

if (!function_exists('aiInstallerGeneratedMarkdownHeaderComment')) {
    /**
     * The hard "DO NOT EDIT" header as a single-line HTML comment (no trailing
     * blank line). Used when inserting after YAML frontmatter so the comment can
     * be placed on its own line directly under the closing `---`.
     */
    function aiInstallerGeneratedMarkdownHeaderComment(string $source): string
    {
        return '<!-- GENERATED — DO NOT EDIT: generated by ' . $source . '. -->';
    }
}

if (!function_exists('aiInstallerInsertGeneratedHeaderAfterFrontmatter')) {
    /**
     * Insert the GENERATED HTML comment header into markdown content in a
     * frontmatter-safe way.
     *
     * - If the content starts with a YAML frontmatter block (`---\n ... \n---`),
     *   the comment is inserted immediately AFTER the closing `---` line so the
     *   frontmatter stays parseable.
     * - Otherwise the comment is prepended at the very top.
     *
     * Idempotent: if the canonical GENERATED marker is already present, the
     * content is returned unchanged (no double insertion).
     */
    function aiInstallerInsertGeneratedHeaderAfterFrontmatter(string $content, string $source): string
    {
        // Idempotency guard: never insert twice.
        if (str_contains($content, '<!-- GENERATED — DO NOT EDIT:')) {
            return $content;
        }

        $comment = aiInstallerGeneratedMarkdownHeaderComment($source);

        // Match a leading frontmatter block: opening --- line, body, closing --- line.
        if (preg_match('/^(---\R.*?\R---\R)/s', $content, $m) === 1) {
            $frontmatter = $m[1];
            $rest = substr($content, strlen($frontmatter));
            return $frontmatter . $comment . "\n" . ($rest === '' ? '' : ($rest[0] === "\n" ? $rest : "\n" . $rest));
        }

        return $comment . "\n\n" . $content;
    }
}
