<?php

declare(strict_types=1);

function aiInstallerScriptRegistry(): array
{
    $scripts = [
        'common' => [
            'label' => 'Shared helper library for AI shell scripts',
            'source_path' => 'scripts/ai/common.sh',
            'installed_path' => 'scripts/ai/common.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'ai-search' => [
            'label' => 'Safe repository text search wrapper',
            'source_path' => 'scripts/ai/ai-search.sh',
            'installed_path' => 'scripts/ai/ai-search.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git', 'jq', 'rg', 'fd', 'ast-grep'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
            'tier' => 'tier1',
            'mutates_state' => false,
            'writes_paths' => [],
            'reads_secret_values' => false,
            'supports_json' => true,
            'bounded_output' => true,
            'requires_approval' => false,
        ],
        'rg-code' => [
            'label' => 'Code-focused ripgrep wrapper',
            'source_path' => 'scripts/ai/rg-code.sh',
            'installed_path' => 'scripts/ai/rg-code.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'rg'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'fd-files' => [
            'label' => 'File discovery wrapper',
            'source_path' => 'scripts/ai/fd-files.sh',
            'installed_path' => 'scripts/ai/fd-files.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'jq', 'rg'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'run-repo-tests' => [
            'label' => 'Parallel-first repository test runner',
            'source_path' => 'scripts/ai/run-repo-tests.sh',
            'installed_path' => 'scripts/ai/run-repo-tests.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'php'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'preview-file' => [
            'label' => 'Safe file preview wrapper',
            'source_path' => 'scripts/ai/preview-file.sh',
            'installed_path' => 'scripts/ai/preview-file.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'jq'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
            'tier' => 'tier1',
            'mutates_state' => false,
            'writes_paths' => [],
            'reads_secret_values' => false,
            'supports_json' => true,
            'bounded_output' => true,
            'requires_approval' => false,
        ],
        'query-usage' => [
            'label' => 'Symbol usage query wrapper',
            'source_path' => 'scripts/ai/query-usage.sh',
            'installed_path' => 'scripts/ai/query-usage.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'rg'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'git-forensics' => [
            'label' => 'Read-only git history tracing wrapper',
            'source_path' => 'scripts/ai/git-forensics.sh',
            'installed_path' => 'scripts/ai/git-forensics.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'gh-pr-context' => [
            'label' => 'GitHub PR context wrapper',
            'source_path' => 'scripts/ai/gh-pr-context.sh',
            'installed_path' => 'scripts/ai/gh-pr-context.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'gh', 'git'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'ai-doc-check' => [
            'label' => 'AI docs consistency checker wrapper',
            'source_path' => 'scripts/ai/ai-doc-check.sh',
            'installed_path' => 'scripts/ai/ai-doc-check.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git', 'rg'],
            'risk' => 'read-only',
            'supports_dry_run' => true,
            'default_args' => ['--check'],
        ],
        'ai-diff-context' => [
            'label' => 'Diff-aware context extraction wrapper',
            'source_path' => 'scripts/ai/ai-diff-context.sh',
            'installed_path' => 'scripts/ai/ai-diff-context.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'ai-verify' => [
            'label' => 'Verification workflow wrapper',
            'source_path' => 'scripts/ai/ai-verify.sh',
            'installed_path' => 'scripts/ai/ai-verify.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
            'tier' => 'tier2',
            'mutates_state' => false,
            'writes_paths' => [],
            'reads_secret_values' => false,
            'supports_json' => false,
            'bounded_output' => true,
            'requires_approval' => true,
        ],
        'ai-rollback' => [
            'label' => 'Rollback snapshot helper',
            'source_path' => 'scripts/ai/ai-rollback.sh',
            'installed_path' => 'scripts/ai/ai-rollback.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git'],
            'risk' => 'mutating',
            'supports_dry_run' => false,
            'default_args' => [],
            'tier' => 'tier3',
            'mutates_state' => true,
            'writes_paths' => ['.ai-logs/', 'docs/ai/generated/'],
            'reads_secret_values' => false,
            'supports_json' => false,
            'bounded_output' => true,
            'requires_approval' => true,
        ],
        'ai-edit' => [
            'label' => 'Scoped repository edit wrapper',
            'source_path' => 'scripts/ai/ai-edit.sh',
            'installed_path' => 'scripts/ai/ai-edit.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git', 'python3'],
            'risk' => 'mutating',
            'supports_dry_run' => true,
            'default_args' => [],
            'tier' => 'tier3',
            'mutates_state' => true,
            'writes_paths' => ['repo-scoped'],
            'reads_secret_values' => false,
            'supports_json' => false,
            'bounded_output' => true,
            'requires_approval' => true,
        ],
        'pre-tool-use' => [
            'label' => 'Pre-tool policy decision hook',
            'source_path' => 'scripts/ai/pre-tool-use.sh',
            'installed_path' => 'scripts/ai/pre-tool-use.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'jq'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
            'tier' => 'tier1',
            'mutates_state' => false,
            'writes_paths' => [],
            'reads_secret_values' => false,
            'supports_json' => true,
            'bounded_output' => true,
            'requires_approval' => false,
        ],
        'post-tool-use' => [
            'label' => 'Post-tool evidence writer hook',
            'source_path' => 'scripts/ai/post-tool-use.sh',
            'installed_path' => 'scripts/ai/post-tool-use.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'jq', 'date'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
            'tier' => 'tier1',
            'mutates_state' => false,
            'writes_paths' => ['.ai-logs/'],
            'reads_secret_values' => false,
            'supports_json' => true,
            'bounded_output' => true,
            'requires_approval' => false,
        ],
        'repomix-context' => [
            'label' => 'Generate Repomix context bundle',
            'source_path' => 'scripts/ai/run-repomix-context.sh',
            'installed_path' => 'scripts/ai/run-repomix-context.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git', 'repomix', 'scc'],
            'risk' => 'read-only',
            'supports_dry_run' => true,
            'default_args' => [],
        ],
        'repomix-file' => [
            'label' => 'Generate Repomix bundle for a single file',
            'source_path' => 'scripts/ai/run-repomix-file.sh',
            'installed_path' => 'scripts/ai/run-repomix-file.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'jq', 'repomix'],
            'risk' => 'read-only',
            'supports_dry_run' => true,
            'default_args' => [],
        ],
        'repomix-tree' => [
            'label' => 'Generate Repomix context tree',
            'source_path' => 'scripts/ai/repomix-context-tree.sh',
            'installed_path' => 'scripts/ai/repomix-context-tree.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git', 'repomix', 'scc'],
            'risk' => 'read-only',
            'supports_dry_run' => true,
            'default_args' => [],
        ],
        'repomix-scc-router' => [
            'label' => 'Generate SCC-ranked Repomix context',
            'source_path' => 'scripts/ai/repomix-scc-router.sh',
            'installed_path' => 'scripts/ai/repomix-scc-router.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git', 'jq', 'rg', 'repomix', 'scc'],
            'risk' => 'read-only',
            'supports_dry_run' => true,
            'default_args' => [],
        ],
        'repomix-freshness' => [
            'label' => 'Check Repomix context bundle freshness (warn 2d, block >7d)',
            'source_path' => 'scripts/ai/repomix-freshness.sh',
            'installed_path' => 'scripts/ai/repomix-freshness.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'jq'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
            'tier' => 'tier1',
            'mutates_state' => false,
            'writes_paths' => [],
            'reads_secret_values' => false,
            'supports_json' => true,
            'bounded_output' => true,
            'requires_approval' => false,
        ],
        'repomix-ensure-fresh' => [
            'label' => 'Ensure Repomix context is fresh; ask-gated, opt-in regeneration',
            'source_path' => 'scripts/ai/repomix-ensure-fresh.sh',
            'installed_path' => 'scripts/ai/repomix-ensure-fresh.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'jq', 'git', 'repomix', 'scc'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
            'tier' => 'tier2',
            'mutates_state' => false,
            'writes_paths' => ['.repomix-context/'],
            'reads_secret_values' => false,
            'supports_json' => false,
            'bounded_output' => true,
            'requires_approval' => true,
        ],
        'pack-context' => [
            'label' => 'Pack AI context bundle',
            'source_path' => 'scripts/ai/pack-context.sh',
            'installed_path' => 'scripts/ai/pack-context.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git', 'jq', 'rg'],
            'risk' => 'read-only',
            'supports_dry_run' => true,
            'default_args' => [],
        ],
        'ai-structured' => [
            'label' => 'Emit structured AI helper output',
            'source_path' => 'scripts/ai/ai-structured.sh',
            'installed_path' => 'scripts/ai/ai-structured.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'jq'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'ai-task' => [
            'label' => 'Task context helper wrapper',
            'source_path' => 'scripts/ai/ai-task.sh',
            'installed_path' => 'scripts/ai/ai-task.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git', 'jq'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'ai-test-select' => [
            'label' => 'Select focused tests for a change',
            'source_path' => 'scripts/ai/ai-test-select.sh',
            'installed_path' => 'scripts/ai/ai-test-select.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'session-checkpoint' => [
            'label' => 'Write AI session checkpoint notes',
            'source_path' => 'scripts/ai/session-checkpoint.sh',
            'installed_path' => 'scripts/ai/session-checkpoint.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git'],
            'risk' => 'mutating',
            'supports_dry_run' => true,
            'default_args' => ['--dry-run'],
        ],
        'ai-file-freshness' => [
            'label' => 'Check AI file freshness signals',
            'source_path' => 'scripts/ai/ai-file-freshness.sh',
            'installed_path' => 'scripts/ai/ai-file-freshness.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'ai-install-coverage' => [
            'label' => 'Check installer pack coverage',
            'source_path' => 'scripts/ai/ai-install-coverage.sh',
            'installed_path' => 'scripts/ai/ai-install-coverage.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'check-file-refs' => [
            'label' => 'Check documentation file references',
            'source_path' => 'scripts/ai/check-file-refs.sh',
            'installed_path' => 'scripts/ai/check-file-refs.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'repo-stats' => [
            'label' => 'Summarize repository file statistics',
            'source_path' => 'scripts/ai/repo-stats.sh',
            'installed_path' => 'scripts/ai/repo-stats.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'repo-tool-inventory' => [
            'label' => 'Generate/check required tools inventory doc',
            'source_path' => 'scripts/ai/repo-tool-inventory.sh',
            'installed_path' => 'scripts/ai/repo-tool-inventory.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'git'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'install-mandatory-tools' => [
            'label' => 'Install mandatory CLI tools by OS',
            'source_path' => 'scripts/ai/install-mandatory-tools.sh',
            'installed_path' => 'scripts/ai/install-mandatory-tools.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash'],
            'risk' => 'mutating',
            'supports_dry_run' => true,
            'default_args' => ['--dry-run'],
            'source_repo_only' => true,
        ],
        'watch-loop' => [
            'label' => 'Watched command retry wrapper',
            'source_path' => 'scripts/ai/watch-loop.sh',
            'installed_path' => 'scripts/ai/watch-loop.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash'],
            'risk' => 'read-only',
            'supports_dry_run' => false,
            'default_args' => [],
        ],
        'prune-shipped-targets' => [
            'label' => 'Kit-author cleanup of shipped-template duplicates',
            'source_path' => 'scripts/ai/prune-shipped-targets.sh',
            'installed_path' => 'scripts/ai/prune-shipped-targets.sh',
            'pack' => 'scripts-pack',
            'required_tools' => ['bash', 'jq', 'git'],
            'risk' => 'mutating',
            'supports_dry_run' => true,
            'default_args' => ['--list'],
            'source_repo_only' => true,
        ],
    ];

    foreach ($scripts as $id => $entry) {
        if (!isset($entry['autonomy_level'])) {
            $scripts[$id]['autonomy_level'] = aiInstallerInferScriptAutonomyLevel($entry);
        }
    }

    return $scripts;
}

function aiInstallerInferScriptAutonomyLevel(array $entry): string
{
    if (($entry['risk'] ?? '') === 'mutating' || ($entry['mutates_state'] ?? false) === true || ($entry['requires_approval'] ?? false) === true) {
        return 'act_with_approval';
    }

    $writesPaths = $entry['writes_paths'] ?? [];
    if (is_array($writesPaths) && $writesPaths !== []) {
        return 'advise';
    }

    if (($entry['supports_dry_run'] ?? false) === true) {
        return 'advise';
    }

    return 'observe';
}

function aiInstallerCommandPolicyRiskTiers(): array
{
    return [
        'tier0' => 'environment probe',
        'tier1' => 'bounded read-only wrapper',
        'tier2' => 'ask-gated mutation-adjacent or broad read',
        'tier3' => 'explicit approval mutation',
        'tier4' => 'deny',
    ];
}
