<?php

declare(strict_types=1);

require_once __DIR__ . '/stack-registry.php';

/**
 * Renders the `scan-stack` skill's committed, human-readable projection of a
 * stack-detection run: `docs/ai/project/stack.md`.
 *
 * Ticket: docs/tickets/arch-todo-stack-permission-placeholder-skill-trio-20260705T151632Z,
 * P4.1/P4.2/P4.2a. Wraps aiStackDetect()/aiStackSelectionResolve() output only —
 * no scanning logic lives here.
 *
 * CRITICAL naming-collision guard: this file's output path is
 * `docs/ai/project/stack.md` (WITH the `/project/` subfolder, alongside the
 * existing `docs/ai/project/project-interaction.md`). It is a categorically
 * different, unrelated artifact from the pre-existing
 * `docs/ai/project-stack.md` (NO `/project/` subfolder — a legacy
 * compatibility shim rendered from `project-stack.template.md` via
 * `packs.php` with `merge_strategy: skip-if-exists`, covered by
 * `UpgradeOwnershipTest` and `UninstallTest`). No function in this file may
 * ever read from, write to, or delete `docs/ai/project-stack.md`.
 */

/** Relative path (from a project root) of this ticket's generated doc. Fixed, not derived. */
function aiStackProjectDocRelativePath(): string
{
    return 'docs/ai/project/stack.md';
}

/** Relative path of the unrelated legacy shim this file must never touch. Exposed only for tests/guards. */
function aiStackLegacyProjectStackRelativePath(): string
{
    return 'docs/ai/project-stack.md';
}

function aiStackProjectDocPath(string $targetRoot): string
{
    return aiStackNormalizeRoot($targetRoot) . '/' . aiStackProjectDocRelativePath();
}

/**
 * @param array{
 *   detected: array<string,array{id:string,confidence:int,signals:list<string>,implied_by?:string,warnings?:list<string>}>,
 *   selected: list<string>,
 *   versions: array<string,array{id:string,tool:string,available:bool,output:string,error?:string,required:bool}>
 * } $resolved
 */
function aiStackRenderProjectDocMarkdown(array $resolved, string $projectLabel = ''): string
{
    $title = trim($projectLabel) === '' ? 'Detected Stack' : trim($projectLabel) . ' Detected Stack';
    $lines = [
        '# ' . $title,
        '',
        'Generated by `php tools/ai/ai.php stack-detect`. This is a point-in-time',
        'projection of the last scan — re-run the command after adding or removing a',
        'language, framework, or toolchain so this file stays current.',
        '',
        'Not to be confused with `docs/ai/project-stack.md` (an unrelated legacy',
        'compatibility shim for older installs). This file lives at',
        '`docs/ai/project/stack.md`, alongside `docs/ai/project/project-interaction.md`.',
        '',
        '## Detected Stacks',
        '',
    ];

    if ($resolved['detected'] === []) {
        $lines[] = 'None detected.';
    } else {
        $lines[] = '| Stack | Confidence | Signals |';
        $lines[] = '|---|---:|---|';
        foreach ($resolved['detected'] as $id => $entry) {
            $signals = implode(', ', $entry['signals']);
            $suffix = isset($entry['implied_by']) ? ' (implied by ' . $entry['implied_by'] . ')' : '';
            $lines[] = sprintf('| `%s`%s | %d | %s |', $id, $suffix, $entry['confidence'], $signals === '' ? '-' : $signals);
        }
    }

    $lines[] = '';
    $lines[] = '## Selected Stacks';
    $lines[] = '';
    $lines[] = $resolved['selected'] === [] ? 'None selected.' : implode(', ', array_map(static fn (string $id): string => '`' . $id . '`', $resolved['selected']));

    $lines[] = '';
    $lines[] = '## Tool Versions';
    $lines[] = '';
    if ($resolved['versions'] === []) {
        $lines[] = 'No version checks ran for the selected stacks.';
    } else {
        $lines[] = '| Tool | Available | Output |';
        $lines[] = '|---|---|---|';
        foreach ($resolved['versions'] as $entry) {
            $output = $entry['available'] ? aiStackFirstLineForDoc($entry['output']) : ($entry['error'] ?? 'unavailable');
            $lines[] = sprintf('| `%s` | %s | %s |', $entry['tool'], $entry['available'] ? 'yes' : 'no', $output === '' ? '-' : $output);
        }
    }

    $lines[] = '';
    $lines[] = '## Metadata';
    $lines[] = '';
    $lines[] = '- Generated at: `' . (new DateTimeImmutable('now', new DateTimeZone('UTC')))->format(DateTimeInterface::ATOM) . '`';
    $lines[] = '- Command: `php tools/ai/ai.php stack-detect`';

    return implode("\n", $lines) . "\n";
}

function aiStackFirstLineForDoc(string $text): string
{
    $parts = preg_split('/\R/', trim($text)) ?: [];

    return (string) ($parts[0] ?? '');
}

/**
 * Writes the rendered doc to `docs/ai/project/stack.md` under `$targetRoot`
 * and returns the absolute path written. Never touches the legacy
 * `docs/ai/project-stack.md` shim — see file-level docblock.
 *
 * @param array{detected:array<string,mixed>,selected:list<string>,versions:array<string,mixed>} $resolved
 */
function aiStackWriteProjectDoc(string $targetRoot, array $resolved, string $projectLabel = ''): string
{
    $path = aiStackProjectDocPath($targetRoot);
    $legacyPath = aiStackNormalizeRoot($targetRoot) . '/' . aiStackLegacyProjectStackRelativePath();
    if ($path === $legacyPath) {
        // Defensive, should be structurally impossible given the two fixed,
        // distinct relative-path strings above — fail loudly rather than risk
        // silently corrupting the legacy compatibility shim.
        throw new RuntimeException('scan-stack output path must never equal the legacy docs/ai/project-stack.md path.');
    }

    $dir = dirname($path);
    if (!is_dir($dir) && !mkdir($dir, 0777, true) && !is_dir($dir)) {
        throw new RuntimeException(sprintf('Could not create directory: %s', $dir));
    }

    file_put_contents($path, aiStackRenderProjectDocMarkdown($resolved, $projectLabel));

    return $path;
}
