<?php

declare(strict_types=1);

namespace Tests;

use PHPUnit\Framework\TestCase;

/**
 * P3: generated-file headers + enforcement.
 *
 * Covers the shared markdown header helper (extracted from the former duplicate
 * definitions in docs.php and manifest.php), the frontmatter-aware insertion used
 * for agent/command/skill markdown, the AGENTS.md template header, the Copilot
 * agent renderer output, the opencode.json soft managed notice, and the hook-JSON
 * `_generated` markers. Also asserts validate-generated-artifacts passes.
 */
final class GeneratedHeaderTest extends TestCase
{
    private static string $repoRoot;

    public static function setUpBeforeClass(): void
    {
        $root = realpath(dirname(__DIR__, 2));
        if ($root === false) {
            throw new \RuntimeException('Could not resolve repo root from tests/php/');
        }
        self::$repoRoot = $root;
        require_once $root . '/tools/ai/install/generated-header.php';
        require_once $root . '/tools/ai/install/copilot-agent-renderer.php';
    }

    public function testSharedHelperReturnsExpectedHeaderString(): void
    {
        self::assertSame(
            '<!-- GENERATED — DO NOT EDIT: generated by my-source. -->' . "\n\n",
            aiInstallerGeneratedMarkdownHeader('my-source')
        );
    }

    public function testSharedHelperIsDefinedExactlyOnceAfterRequireChain(): void
    {
        // Loading the full require chain (which pulls in both manifest.php and docs.php,
        // each requiring generated-header.php) must not trigger a redeclaration fatal.
        require_once self::$repoRoot . '/tools/ai/install/core.php';

        self::assertTrue(function_exists('aiInstallerGeneratedMarkdownHeader'));
        self::assertTrue(function_exists('aiInstallerInsertGeneratedHeaderAfterFrontmatter'));
    }

    public function testFrontmatterAwareInsertionPlacesCommentAfterClosingFence(): void
    {
        $content = "---\nid: architect\nmode: all\n---\n\n# Body\n\nText.\n";
        $result = aiInstallerInsertGeneratedHeaderAfterFrontmatter($content, 'src');

        // Frontmatter must still open at byte 0 so YAML parsing stays valid.
        self::assertStringStartsWith("---\n", $result);

        // The comment must appear AFTER the closing ---, never before the opening ---.
        $closingPos = strpos($result, "\n---\n");
        self::assertNotFalse($closingPos);
        $commentPos = strpos($result, '<!-- GENERATED — DO NOT EDIT:');
        self::assertNotFalse($commentPos);
        self::assertGreaterThan($closingPos, $commentPos, 'comment must follow the closing frontmatter fence');

        // Frontmatter block remains parseable (extractable as a contiguous --- ... --- block).
        self::assertSame(1, preg_match('/^---\R(.*?)\R---\R/s', $result, $m));
        self::assertStringContainsString('id: architect', $m[1]);
        self::assertStringNotContainsString('GENERATED', $m[1]);
    }

    public function testFrontmatterAwareInsertionPrependsWhenNoFrontmatter(): void
    {
        $content = "# Plain markdown\n\nNo frontmatter here.\n";
        $result = aiInstallerInsertGeneratedHeaderAfterFrontmatter($content, 'src');

        self::assertStringStartsWith('<!-- GENERATED — DO NOT EDIT:', $result);
        self::assertStringContainsString('# Plain markdown', $result);
    }

    public function testFrontmatterAwareInsertionIsIdempotent(): void
    {
        $content = "---\nid: x\n---\n\nBody\n";
        $once = aiInstallerInsertGeneratedHeaderAfterFrontmatter($content, 'src');
        $twice = aiInstallerInsertGeneratedHeaderAfterFrontmatter($once, 'src');

        self::assertSame($once, $twice, 'second insertion must not duplicate the marker');
        self::assertSame(1, substr_count($twice, '<!-- GENERATED — DO NOT EDIT:'));
    }

    public function testAgentsTemplateStartsWithGeneratedComment(): void
    {
        $path = self::$repoRoot . '/packages/ai-universal-rules/templates/core/AGENTS.template.md';
        self::assertFileExists($path);
        $content = (string) file_get_contents($path);

        self::assertStringStartsWith('<!-- GENERATED — DO NOT EDIT:', $content);
        // Header must not contain placeholder tokens that would collide with substitution.
        $firstLine = strtok($content, "\n");
        self::assertIsString($firstLine);
        self::assertSame(0, preg_match('/<[A-Z0-9_]+>/', $firstLine), 'header must not carry <PLACEHOLDER> tokens');
    }

    public function testRenderedCopilotAgentCarriesMarkerAfterFrontmatter(): void
    {
        $srcContent = "---\nid: architect\ndescription: Demo agent\nmode: all\n---\n\n# Architect\n\nBody.\n";
        $rendered = aiInstallerRenderCopilotAgent($srcContent, 'architect', 'scripts/ai');

        self::assertStringStartsWith("---\n", $rendered, 'Copilot frontmatter must open the file');
        self::assertStringContainsString('<!-- GENERATED — DO NOT EDIT:', $rendered);

        // The marker must come after the Copilot frontmatter block.
        self::assertSame(1, preg_match('/^---\R(.*?)\R---\R/s', $rendered, $m));
        self::assertStringNotContainsString('GENERATED', $m[1], 'marker must not land inside frontmatter');
    }

    public function testOpencodeTemplateHasSoftManagedNoticeAndParsesAsJsonc(): void
    {
        $path = self::$repoRoot . '/packages/ai-universal-rules/templates/core/opencode.json';
        self::assertFileExists($path);
        $raw = (string) file_get_contents($path);

        self::assertStringContainsString('// Managed by ai-kit.', $raw);
        // Must NOT use the hard "DO NOT EDIT" header (soft notice only, per adopt/conflict semantics).
        self::assertStringNotContainsString('DO NOT EDIT', $raw);

        // Round-trips through the installer's JSONC parse (comment stripping) as used by validators.
        $stripped = $this->stripJsonc($raw);
        $decoded = json_decode($stripped, true);
        self::assertIsArray($decoded, 'opencode.json must decode after JSONC comment stripping');
        self::assertArrayHasKey('permission', $decoded);
    }

    public function testHookJsonFilesCarryGeneratedMarkerAndRemainValidJson(): void
    {
        foreach ([
            'packages/ai-universal-rules/templates/github/hooks/tool-policy.json',
            'packages/ai-universal-rules/templates/github/hooks/tool-guardian.json',
        ] as $relative) {
            $path = self::$repoRoot . '/' . $relative;
            self::assertFileExists($path);
            $decoded = json_decode((string) file_get_contents($path), true);
            self::assertIsArray($decoded, "{$relative} must be valid JSON");
            self::assertSame('ai-kit', $decoded['_generated']['tool'] ?? null, "{$relative} must declare _generated.tool == ai-kit");
        }
    }

    public function testValidateGeneratedArtifactsPasses(): void
    {
        $descriptors = [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']];
        $command = escapeshellarg((string) PHP_BINARY) . ' tools/ai/validate-generated-artifacts.php';
        $process = proc_open($command, $descriptors, $pipes, self::$repoRoot);
        self::assertIsResource($process);
        fclose($pipes[0]);
        $stdout = (string) stream_get_contents($pipes[1]);
        $stderr = (string) stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);
        $exit = proc_close($process);

        self::assertSame(0, $exit, "validate-generated-artifacts failed:\n{$stdout}\n{$stderr}");
    }

    private function stripJsonc(string $input): string
    {
        $out = '';
        $inString = false;
        $escaped = false;
        $inLine = false;
        $inBlock = false;
        $length = strlen($input);

        for ($i = 0; $i < $length; $i++) {
            $char = $input[$i];
            $next = $i + 1 < $length ? $input[$i + 1] : '';

            if ($inLine) {
                if ($char === "\n") {
                    $inLine = false;
                    $out .= $char;
                }
                continue;
            }
            if ($inBlock) {
                if ($char === '*' && $next === '/') {
                    $inBlock = false;
                    $i++;
                }
                continue;
            }
            if ($inString) {
                $out .= $char;
                if ($escaped) {
                    $escaped = false;
                } elseif ($char === '\\') {
                    $escaped = true;
                } elseif ($char === '"') {
                    $inString = false;
                }
                continue;
            }
            if ($char === '"') {
                $inString = true;
                $out .= $char;
                continue;
            }
            if ($char === '/' && $next === '/') {
                $inLine = true;
                $i++;
                continue;
            }
            if ($char === '/' && $next === '*') {
                $inBlock = true;
                $i++;
                continue;
            }
            $out .= $char;
        }

        return (string) preg_replace('/,(\s*[}\]])/', '$1', $out);
    }
}
